name: gameon
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: 2.15.1
  firebase_auth: ^4.9.0
  iconly: ^1.0.1
  firebase_storage: ^11.2.6
  image_picker: ^1.0.4
  lottie: ^2.6.0
  animated_text_kit: ^4.2.2
  cloud_firestore: ^4.9.1
  google_fonts: ^6.0.0
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/svgs/
    - assets/images/
